version: '3.0'

services:

  nginx:
    build:
      context: ./docker/nginx
    environment:
      - VIRTUAL_HOST=test.pstuffapp.com
    depends_on:
      - php
    volumes:
      - ./logs:/var/log/nginx
      - ./:/var/www/html
    networks:
      - default
      - backend

  php:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./:/var/www/html
    networks:
      - backend

  db:
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    volumes:
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    environment:
      - VIRTUAL_HOST=pmatest.pstuffapp.com
      - PMA_HOST=${DB_HOST}
    networks:
      - default
      - backend

networks:
  default:
    external:
      name: nginxproxy_proxy
  frontend:
  backend:
